apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:YxSA2ZD7DqM6kokQL7ZelH7XNxqM6HLxHZAryyXsZITClI4jPulY4w==,iv:7ejd3kkL5CtVLIxkK1/OohldLSr0Fs/Ee5EpgL8UdfY=,tag:kDI3PV3+UnDPm7DpjjgD+g==,type:str]
sops:
  age:
    - recipient: age1hppg8237f0zc2pq7x6rqmd4zqsk048z78f8rcyqeaumj2mjx8qdqcfgm86
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZWUyQXdRbll4QXg3N3Ns
        ZzZYb3A1U1hGQzlhMDQ4cDIwZk43Mzh0cWdFCjJrRmswUnpUNlZHNTBXQTJTYjAr
        eGc3cG5HNnVzdHpJMTBsSnNESTRPNEEKLS0tIEI5VGtZdUdMZS9WY2JwaE8rWWNY
        dmdTWEhtVDdKU3RqaGVUVHlYbSsvWWcKc5Mk6XS1XIuslV9XxlqJQu5/LlIHcxMX
        SBdQ5A6hsPvC1RPDTxbW673IXs6HzZjLAIAF/l3dRlOBRoZ1uSSdlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T01:29:44Z"
  mac: ENC[AES256_GCM,data:zDQ7Moj3ujEOfIjuiayh5CsG2rqDo9wESHNamqmlQB9Z3GyCp4Gt7O45A2AxocPMFLjkZI2ytEyUW/CQJJ4JpVxGEq7n1r5eFZ/ZNvmX6iL35aCm7bQ6sUrEsJvYXwoTvglxGdyLMIdJIP480VbmQmb5v/DwvJVFvNxBcVhKplA=,iv:7oCGpOURL+HlBOQLyerPM+u28fobUsYfBoJyj/Vp6q8=,tag:Dyf3V5t+Y+eGqNHmQ0Y5eA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
