apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:89DcBvl7HyLT,iv:+7lDURfw62Dn2/+hDk1dIIeLRxEOwzK2jc0Q8j+urGY=,tag:avqc2BRBIMMYU1sFBYtufA==,type:str]
sops:
  age:
    - recipient: age1hppg8237f0zc2pq7x6rqmd4zqsk048z78f8rcyqeaumj2mjx8qdqcfgm86
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaHQxYTdDYVJVRDJzeUM5
        cG83S0cySFdTbkZyNksyYlZVelZEdmNiZVZFCjVKL1BNdmo2alVrV3EwWksxTDN0
        TS91MFEyWllkc1VzY0s1UWNMNmRZbGMKLS0tIGp6NXIwNHdOQXB3VnJ2eWpnbWhS
        Q3NNUEpiSmNwcEFEbllVNFoxUlJQOWsK2Q6Bx/VI3OS1xfdwhO3bDFy3U3YJfrhp
        QGDx6xmmeOrdSam7NMayMQLPTCPiF8oLMhvs9kM1S5j+IZxQL9XCnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T01:29:44Z"
  mac: ENC[AES256_GCM,data:cKIt6WjCxkZaIjVTFFHxMh5X0Cb7ewBcCCp777l0G0hznfJlKvrzYxg4Wa0RTIbPKJX7wdf52NlM9+BumX/+tpN9pzzSGciUKMmtuHX08u8sqg045LLhcE7HmM31YJLNpINtHYiFqAGGDlHyysVnpRbtvKVQXBAPlKV8Qq4Qmfc=,iv:SAwCO9JKb81qpDkIEZUAMOTtkGRXZLsF3ZCRfIZnht0=,tag:d/yZVJFz+FO4Oy/TsbN+cA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
