apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:28+x3CHXQOs4EfDASZYjxDTK9mnvueiV+VPeE6ki5P0=,iv:49q23abgdwcojIOJiXFldovnWSk2BMvII2q4qQjYdxs=,tag:3hdCyR1zAEPkMCeUMEWaxg==,type:str]
sops:
  age:
    - recipient: age1hppg8237f0zc2pq7x6rqmd4zqsk048z78f8rcyqeaumj2mjx8qdqcfgm86
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaSt5VWFRWFpYZHJTZ1Yx
        UjhneEF5c0hZVUJKSnBhY0RoVU9lMzNNdmw4CndjVEV1ZkIrMVY1cXQwSEppN0pz
        VkJOMVJwcW5BQkJsQldoT2J2YTE0ZDgKLS0tIExFdk9Ua1gyUFpYRmsvVDFBb0ZW
        UW5TektTb2tENXpNRkZxWm5XOU04RmMKkB7WV2v9XirLSRowmwUt90qvEmk2NOsg
        JSpPP4kUb0UoElgJoRaxUU02w7r321Clp1EB//8+vhHxMq7IS4CPDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T01:29:44Z"
  mac: ENC[AES256_GCM,data:ZI/mD4ihQVgb8HcVS8xOvWGwNgph0osdRoe+iGRtsZMNjm5voRiOHKP+GLMu110E6sCXyiWdu+CMYJ387RmWNaVJKcdtzzw/1sY3trzGtPix5rn/veSnkjRRhhOKvEkR8r9UhKuCRAy8Uk+Sr8uuKRNXJqBIGjh9WCmBXL0dGBg=,iv:Z8NBPy5+skxZ38MiZs2eA+PLSHOUBib487TKSbbdlfU=,tag:JJxYcHUNDQvV5BqMhu4Yww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
