apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:QvCSICm2urxf36MrmcGwie8+GklEluH+dmvt/7NLiTe8xzj9kXI9g0kl+sYa0nAKq+2r3U76ghu+jdArpRY6McRZRQ6ExCzfRcQKR/BBDhhJKGJhz/v2GGfSzSHPWYNxW2YuecxPIzeGiBwSBJv5mUPLz4rgPZ0CgutPt78k1SgeQH5M2ZxYdSxcY6OKI58utQXOvaTE/FYTHxikNC6YFfDzc6RCKcRHyPwi1PjjuAxbxsDN,iv:2EvRT7ZmMgm63d/lO41CtPq48+9kMIiqXZf4GAtWhFw=,tag:kI4RkHy8zOa37Pdfo2W5Pw==,type:str]
sops:
  age:
    - recipient: age1hppg8237f0zc2pq7x6rqmd4zqsk048z78f8rcyqeaumj2mjx8qdqcfgm86
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WWl4QmNnZ245WEtJM2U3
        bHNtYklzdUFEckc2WTE4eGhiT2NCd0hjWkZnCnVGNzdVa21tSGJ0NkhQaFUxWjZK
        N0c2VnBlZy8ya3MzU0plUXFsWDRjeEkKLS0tIFYrWkYvUXMzR0V6VUZFTXRvZVUz
        R1d4YWxGMkpEM3ZLdk5Vd0tGWjNScEkKEUwD6ZqCj0bcVz5GRphFoX09gsaTsQJd
        ljoh9UkkniGhbs3QXFz9hacEPsB+3xcK0Si539uB7V1bmVDoKKi6OQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T01:29:44Z"
  mac: ENC[AES256_GCM,data:o5cm2SvzT154FI0bxE99pp6nnYfZzF8sSN0tE7I1u8wzXvGS/SAwBY/s5HKlf6SzXSkHVARhmxx3jzxteyPHlC9HoCJj7jpUHdUV/L6a4Ba3sU6MDnK4XTFLuXkeENYNNdQ/0JLY0p3t+Ty0f4P9o8HoGLXh2WeQHqF+cibTdLc=,iv:cgZCNZ7ku7FY19Q2OtKwFtYCWd/9iEboZ9jDDMK1J90=,tag:7YlOL+6SuXU93vS37ml3Wg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
