apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:vdDPC0ur1Ga4BYqPkLvFNrix2wqH3tsxWeSsPSgyVWiaiwkIOPb4qw==,iv:zShCgHbtY/UgdItxczfcE9oKF5AEkSVCGwq5A744IJU=,tag:smgYJvYOzOy5C0lg74R4kQ==,type:str]
sops:
  age:
    - recipient: age1hppg8237f0zc2pq7x6rqmd4zqsk048z78f8rcyqeaumj2mjx8qdqcfgm86
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OWhXQWE0TEJ2WCtjd1BK
        T3diSWZxOUwyQnZpYS9oNEFPVURvRC8vUVRVCnRHdGR5RzRibG1FUWJOMmRSK0NS
        Y1d2VzA4a3NLY3Z3TTJxVzFyT2IyaDgKLS0tIDZIMlRzc0JBNHBCWDFTVEg2Mk4x
        ejdnSWhoUTdFMDdXMXlrQTJSYVRTYUkKDydOU4EbuOZ8jasXxgMJ/LGxkdg6kuxo
        MiGSKLPvJzLMIyuk1fJydWGqM8p3yD9ppjXK2nSgYG1MK6pILB0TwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T01:29:44Z"
  mac: ENC[AES256_GCM,data:uQSIaGiZflU/KzrxwZyKxUCALbzU3lMJcjHysZuN7UMu+GOvUx0X+Ct6kDgoK5IoLNIoUIHevp3+0JiEQkK29KZUVilyUTYR2db5O3R3duqhIJv8FmenMhXW1BrA6daZa+j6CGXnd98n4bzyJXBcTCwhB+QAvKfyrknTp+yidqo=,iv:fZmXaiS0joYkSskmGQ0woOH/hpt3Zvf1hEUfOD97Y7g=,tag:bqbPBskPt72ss0XPRaJ+gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
